### ISSUE TITLE
Error run the tool with 'cotone'-files' folder

### ISSUE THREAD

**Issue by GustavoVale** [riselabs-ufba/cotonet#4]
when I run Cotonet without delete the output folder (created in the previous time I run the tool) I got an error. It happens even if I delete the .sh file in scripts folder.

**Comment by alcemirsantos** [comment]
This is really strange. Can you be more specific? Which is the error exactly? An exception? Any message?

**Comment by GustavoVale** [comment]
This is the message I have in the Console:

Removing old file: /home/vale/workspace/cotonet/cotonet-files/scripts/run_target-systems.sh
Exception in thread "pool-1-thread-1" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at br.com.riselabs.cotonet.util.CodefaceHelper.createReleasesString(CodefaceHelper.java:288)
	at br.com.riselabs.cotonet.util.CodefaceHelper.createCodefaceConfFiles(CodefaceHelper.java:116)
	at br.com.riselabs.cotonet.crawler.RepositoryCrawler.run(RepositoryCrawler.java:120)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alcemirsantos** [comment]
> at br.com.riselabs.cotonet.util.CodefaceHelper.createReleasesString(CodefaceHelper.java:288)
> at br.com.riselabs.cotonet.util.CodefaceHelper.createCodefaceConfFiles(CodefaceHelper.java:116)

This is probably due the changes you have made recently. This CodefaceHelper class is useful to prepare the `codeface` execution. It is probably failing to do it because of your changes.

My suggestion: Comment the call of the helper in the `run()` of the `ReopositoryCrawler` at the line 120:
> at br.com.riselabs.cotonet.crawler.RepositoryCrawler.run(RepositoryCrawler.java:120)

After we finish the changes we need we get back to it. I will let this issue open until there.

**Comment by xai** [comment]
I think it is a rather old bug. I prepared a branch (based on GustavoVale/fix-conflicts) including a fix. I'll open a pull request when pull request #5 is merged.

**Comment by alcemirsantos** [comment]
@xai  I just merged the pull request number #5.

**Comment by xai** [comment]
OK great, this evening I'll rebase my branches against your master and create more pull requests.

**Comment by alcemirsantos** [comment]
I've merged the your pull request #6, which was meant of fix this problem. Thus, I am closing this issue.
